language: python
services:
  - postgresql

python:
  - "3.6"
addons:
  postgresql: "9.6"

cache:
  directories:
    - $HOME/.cache/pip
    - data

env:
  - PGUSER=postgres

install:
  - pip install .

before_script:
  - psql -c 'show server_version;'
  - psql -f sql/*.sql
  - bash download_data.sh

script:
  - bash test_cli.sh
  - pytest

notifications:
  email: false

