language: python
sudo: false
dist: trusty
services:
  - postgresql

python:
  - "3.6"
addons:
  postgresql: "9.6"

cache:
  directories:
    - $HOME/.cache/pip
    - data

env:
  - PGUSER=postgres

install:
  - pip install .

before_script:
  - psql -c 'show server_version;'
  - psql -f sql/01-create.sql
  - psql -f sql/02-views.sql
  - bash download_data.sh

script:
  - abcd read data/*.xyz
  - pytest
  - bats test_cli/*

notifications:
  email: false

