language: python
services:
  - postgresql

python:
  - "3.6"

env:
  - ABCD_DB='postgresql://postgres@localhost/abcd'

install:
  - pip install -r requirements.txt

before_script:
  - psql -c 'create database abcd;' -U postgres

script:
  - test.sh
