language: python
services:
  - postgresql

python:
  - "3.6"

env:
  - ABCD_DB="postgresql://postgres@localhost/abcd"

install:
  - pip install -r requirements.txt

before_script:
  - psql -U postgres -c 'create database abcd;'
  - psql -U postgres -d abcd -f sql/create.sql
  - psql -U postgres -d abcd -f sql/views.sql

script:
  - bash test.sh
