language: python
services:
  - postgresql

python:
  - "3.6"
addons:
  postgresql: "9.6"

cache:
  directories:
    - $HOME/.cache/pip
    - data

env:
  - PGUSER=postgres
  - ABCD_DB="postgresql://postgres@localhost/abcd"

install:
  - pip install -r requirements.txt

before_script:
  - psql -c 'show server_version;'
  - psql -c 'create database abcd;'
  - psql -d abcd -f sql/create.sql
  - psql -d abcd -f sql/views.sql
  - bash download_data.sh

script:
  - bash test_cli.sh
  - pytest
